### ISSUE TITLE
How to use the camera_tr_rig.yaml file in stereo calibration?

### ISSUE THREAD

**Issue by painterdrown** [puzzlepaint/camera_calibration#59]
Hi @puzzlepaint,

I've tried the stereo calibration using the center_generic model. I got a `camera_tr_rig.yaml` file as following, which looks like the extrinsics. How do you mean by "pattern to image with right-multiplication"? Could you give any formula to explain **how to rotate and translate a 3D point from pattern to image** for camera0 and camera1? Thanks in advance!

```
# Each pose gives the image_tr_pattern transformation (i.e., pattern to image with right-multiplication). Quaternions are written as used by the Eigen library.
pose_count: 2
poses:
  - index: 0
    tx: 0.036815416006008
    ty: -0.0084184475482635
    tz: -0.043255182527781
    qx: -0.011200312422074
    qy: -0.047356321325439
    qz: -0.0038872219716976
    qw: 0.99880769987897
  - index: 1
    tx: -0.0491527029587
    ty: -0.01048828971337
    tz: -0.036783592975036
    qx: -0.021375818177436
    qy: -0.032471644292708
    qz: -0.00073913467043247
    qw: 0.99924377425837
```

By the way, I compared my stereo calibration result with [Tango](https://drive.google.com/file/d/1AQOv4GF5m-Wf2scV6j2O7HETSYrA9aYV/view)'s result that you provided. It seems that Tango's reprojection errors are several times smaller than mine. How can I improve the accuracy?

My results:
```
# report_camera0_info.txt

resolution : 640 x 360
horizontal_fov : 162.10778348606
vertical_fov : 89.687334966321

num_localized_imagesets : 2642
num_total_imagesets : 3792

reprojection_error_count : 676939
reprojection_error_median : 0.08356129266047
reprojection_error_average : 0.10238463680257
reprojection_error_maximum : 0.86268035647455
median_kl_divergence : 0.2594040565522

reprojection_error_histogram_visualization_half_extent_in_pixels : 0.20000000298023
maximum_error_visualization_maximum_error_in_pixels : 0.5
```
```
# report_camera1_info.txt

resolution : 640 x 360
horizontal_fov : 162.01807167622
vertical_fov : 89.580793893326

num_localized_imagesets : 2642
num_total_imagesets : 3792

reprojection_error_count : 645241
reprojection_error_median : 0.078510788397581
reprojection_error_average : 0.096543207437034
reprojection_error_maximum : 0.72272741762914
median_kl_divergence : 0.30343142374995

reprojection_error_histogram_visualization_half_extent_in_pixels : 0.20000000298023
maximum_error_visualization_maximum_error_in_pixels : 0.5
```

Tango's result:
```
# report_camera0_info.txt

resolution : 640 x 480
horizontal_fov : 131.25369038653
vertical_fov : 98.767456956831

num_localized_imagesets : 2535
num_total_imagesets : 2538

reprojection_error_count : 560102
reprojection_error_median : 0.019334347895282
reprojection_error_average : 0.022572707715345
reprojection_error_maximum : 0.1796666238044
median_kl_divergence : 0.23885239818988

reprojection_error_histogram_visualization_half_extent_in_pixels : 0.20000000298023
maximum_error_visualization_maximum_error_in_pixels : 0.5
```
