### ISSUE TITLE
Using a A0 dimension checkerboard means I have to change YAML AprilTag?

### ISSUE THREAD

**Issue by LulaSan** [puzzlepaint/camera_calibration#76]
hello, I am calibrating without success my camera and now using an A0 checkerboard (because it is a very wide camera and I need to use it for long ranges purposes).

I realised the YAML file generated it is referring to A4 dimensions. Should I change them with the A0 ones? 
Also, if the checkerboard I show is rotated with respect to pdf, could this be a problem??

Thanks!
PS: this is the yaml file, 210 and 297 are in a4 format indeed.
```
num_star_segments: 16
squares_x: 17
squares_y: 24
square_length_in_meters: 0.011882352941176469
page:
    width_mm: 210.0
    height_mm: 297.0
    pattern_start_x_mm: 4.0
    pattern_start_y_mm: 5.911764705882365
    pattern_end_x_mm: 205.99999999999997
    pattern_end_y_mm: 291.0882352941177
apriltags:
  - tag_x: 6
    tag_y: 10
    width: 4
    height: 4
    index: 0
```
